#include<bits/stdc++.h>
using namespace std;
struct node_t {
    uint8_t num_elements;
};


template<std::size_t N>
struct node_x_t {
    static_assert(N <= 256, "N must be <= 256");
    node_t base;
    char chars[N];
    node_t* children[N];

    void setChild(size_t index, node_t* child, void* prev) {
        children[index] = static_cast<node_t*>(child);
    }

    node_t* setObject(int idx, node_t* nav){
        nav = children[idx];
        return nav;
    }

    node_x_t(){

    }

    node_x_t(int num, char *a, node_t* b[],char currChar){
        base.num_elements = num+1;
        for(int i=0;i<base.num_elements-1;i++){
            chars[i] = a[i];
            children[i] = b[i];
        }
        chars[base.num_elements-1] = currChar;
        children[base.num_elements-1] = NULL;
    }
};

node_t* assignObject(node_t* current, char key){
    switch(current->num_elements){
        case 1:return ((node_t*)new node_x_t<2>(((node_x_t<1>*)current)->base.num_elements, ((node_x_t<1>*)current)->chars, ((node_x_t<1>*)current)->children,key));break;
        case 2:return ((node_t*)new node_x_t<3>(((node_x_t<2>*)current)->base.num_elements, ((node_x_t<2>*)current)->chars, ((node_x_t<2>*)current)->children,key));break;
        case 3:return ((node_t*)new node_x_t<4>(((node_x_t<3>*)current)->base.num_elements, ((node_x_t<3>*)current)->chars, ((node_x_t<3>*)current)->children,key));break;
        case 4:return ((node_t*)new node_x_t<5>(((node_x_t<4>*)current)->base.num_elements, ((node_x_t<4>*)current)->chars, ((node_x_t<4>*)current)->children,key));break;
        case 5:return ((node_t*)new node_x_t<6>(((node_x_t<5>*)current)->base.num_elements, ((node_x_t<5>*)current)->chars, ((node_x_t<5>*)current)->children,key));break;
        case 6:return ((node_t*)new node_x_t<7>(((node_x_t<6>*)current)->base.num_elements, ((node_x_t<6>*)current)->chars, ((node_x_t<6>*)current)->children,key));break;
        case 7:return ((node_t*)new node_x_t<8>(((node_x_t<7>*)current)->base.num_elements, ((node_x_t<7>*)current)->chars, ((node_x_t<7>*)current)->children,key));break;
        case 8:return ((node_t*)new node_x_t<9>(((node_x_t<8>*)current)->base.num_elements, ((node_x_t<8>*)current)->chars, ((node_x_t<8>*)current)->children,key));break;
        case 9:return ((node_t*)new node_x_t<10>(((node_x_t<9>*)current)->base.num_elements, ((node_x_t<9>*)current)->chars, ((node_x_t<9>*)current)->children,key));break;
        case 10:return ((node_t*)new node_x_t<11>(((node_x_t<10>*)current)->base.num_elements, ((node_x_t<10>*)current)->chars, ((node_x_t<10>*)current)->children,key));break;
        case 11:return ((node_t*)new node_x_t<12>(((node_x_t<11>*)current)->base.num_elements, ((node_x_t<11>*)current)->chars, ((node_x_t<11>*)current)->children,key));break;
        case 12:return ((node_t*)new node_x_t<13>(((node_x_t<12>*)current)->base.num_elements, ((node_x_t<12>*)current)->chars, ((node_x_t<12>*)current)->children,key));break;
        case 13:return ((node_t*)new node_x_t<14>(((node_x_t<13>*)current)->base.num_elements, ((node_x_t<13>*)current)->chars, ((node_x_t<13>*)current)->children,key));break;
        case 14:return ((node_t*)new node_x_t<15>(((node_x_t<14>*)current)->base.num_elements, ((node_x_t<14>*)current)->chars, ((node_x_t<14>*)current)->children,key));break;
        case 15:return ((node_t*)new node_x_t<16>(((node_x_t<15>*)current)->base.num_elements, ((node_x_t<15>*)current)->chars, ((node_x_t<15>*)current)->children,key));break;
        case 16:return ((node_t*)new node_x_t<17>(((node_x_t<16>*)current)->base.num_elements, ((node_x_t<16>*)current)->chars, ((node_x_t<16>*)current)->children,key));break;
        case 17:return ((node_t*)new node_x_t<18>(((node_x_t<17>*)current)->base.num_elements, ((node_x_t<17>*)current)->chars, ((node_x_t<17>*)current)->children,key));break;
        case 18:return ((node_t*)new node_x_t<19>(((node_x_t<18>*)current)->base.num_elements, ((node_x_t<18>*)current)->chars, ((node_x_t<18>*)current)->children,key));break;
        case 19:return ((node_t*)new node_x_t<20>(((node_x_t<19>*)current)->base.num_elements, ((node_x_t<19>*)current)->chars, ((node_x_t<19>*)current)->children,key));break;
        case 20:return ((node_t*)new node_x_t<21>(((node_x_t<20>*)current)->base.num_elements, ((node_x_t<20>*)current)->chars, ((node_x_t<20>*)current)->children,key));break;
        case 21:return ((node_t*)new node_x_t<22>(((node_x_t<21>*)current)->base.num_elements, ((node_x_t<21>*)current)->chars, ((node_x_t<21>*)current)->children,key));break;
        case 22:return ((node_t*)new node_x_t<23>(((node_x_t<22>*)current)->base.num_elements, ((node_x_t<22>*)current)->chars, ((node_x_t<22>*)current)->children,key));break;
        case 23:return ((node_t*)new node_x_t<24>(((node_x_t<23>*)current)->base.num_elements, ((node_x_t<23>*)current)->chars, ((node_x_t<23>*)current)->children,key));break;
        case 24:return ((node_t*)new node_x_t<25>(((node_x_t<24>*)current)->base.num_elements, ((node_x_t<24>*)current)->chars, ((node_x_t<24>*)current)->children,key));break;
        case 25:return ((node_t*)new node_x_t<26>(((node_x_t<25>*)current)->base.num_elements, ((node_x_t<25>*)current)->chars, ((node_x_t<25>*)current)->children,key));break;
        case 26:return ((node_t*)new node_x_t<27>(((node_x_t<26>*)current)->base.num_elements, ((node_x_t<26>*)current)->chars, ((node_x_t<26>*)current)->children,key));break;
        case 27:return ((node_t*)new node_x_t<28>(((node_x_t<27>*)current)->base.num_elements, ((node_x_t<27>*)current)->chars, ((node_x_t<27>*)current)->children,key));break;
        case 28:return ((node_t*)new node_x_t<29>(((node_x_t<28>*)current)->base.num_elements, ((node_x_t<28>*)current)->chars, ((node_x_t<28>*)current)->children,key));break;
        case 29:return ((node_t*)new node_x_t<30>(((node_x_t<29>*)current)->base.num_elements, ((node_x_t<29>*)current)->chars, ((node_x_t<29>*)current)->children,key));break;
        case 30:return ((node_t*)new node_x_t<31>(((node_x_t<30>*)current)->base.num_elements, ((node_x_t<30>*)current)->chars, ((node_x_t<30>*)current)->children,key));break;
        case 31:return ((node_t*)new node_x_t<32>(((node_x_t<31>*)current)->base.num_elements, ((node_x_t<31>*)current)->chars, ((node_x_t<31>*)current)->children,key));break;
        case 32:return ((node_t*)new node_x_t<33>(((node_x_t<32>*)current)->base.num_elements, ((node_x_t<32>*)current)->chars, ((node_x_t<32>*)current)->children,key));break;
        case 33:return ((node_t*)new node_x_t<34>(((node_x_t<33>*)current)->base.num_elements, ((node_x_t<33>*)current)->chars, ((node_x_t<33>*)current)->children,key));break;
        case 34:return ((node_t*)new node_x_t<35>(((node_x_t<34>*)current)->base.num_elements, ((node_x_t<34>*)current)->chars, ((node_x_t<34>*)current)->children,key));break;
        case 35:return ((node_t*)new node_x_t<36>(((node_x_t<35>*)current)->base.num_elements, ((node_x_t<35>*)current)->chars, ((node_x_t<35>*)current)->children,key));break;
        case 36:return ((node_t*)new node_x_t<37>(((node_x_t<36>*)current)->base.num_elements, ((node_x_t<36>*)current)->chars, ((node_x_t<36>*)current)->children,key));break;
        case 37:return ((node_t*)new node_x_t<38>(((node_x_t<37>*)current)->base.num_elements, ((node_x_t<37>*)current)->chars, ((node_x_t<37>*)current)->children,key));break;
        case 38:return ((node_t*)new node_x_t<39>(((node_x_t<38>*)current)->base.num_elements, ((node_x_t<38>*)current)->chars, ((node_x_t<38>*)current)->children,key));break;
        case 39:return ((node_t*)new node_x_t<40>(((node_x_t<39>*)current)->base.num_elements, ((node_x_t<39>*)current)->chars, ((node_x_t<39>*)current)->children,key));break;
        case 40:return ((node_t*)new node_x_t<41>(((node_x_t<40>*)current)->base.num_elements, ((node_x_t<40>*)current)->chars, ((node_x_t<40>*)current)->children,key));break;
        case 41:return ((node_t*)new node_x_t<42>(((node_x_t<41>*)current)->base.num_elements, ((node_x_t<41>*)current)->chars, ((node_x_t<41>*)current)->children,key));break;
        case 42:return ((node_t*)new node_x_t<43>(((node_x_t<42>*)current)->base.num_elements, ((node_x_t<42>*)current)->chars, ((node_x_t<42>*)current)->children,key));break;
        case 43:return ((node_t*)new node_x_t<44>(((node_x_t<43>*)current)->base.num_elements, ((node_x_t<43>*)current)->chars, ((node_x_t<43>*)current)->children,key));break;
        case 44:return ((node_t*)new node_x_t<45>(((node_x_t<44>*)current)->base.num_elements, ((node_x_t<44>*)current)->chars, ((node_x_t<44>*)current)->children,key));break;
        case 45:return ((node_t*)new node_x_t<46>(((node_x_t<45>*)current)->base.num_elements, ((node_x_t<45>*)current)->chars, ((node_x_t<45>*)current)->children,key));break;
        case 46:return ((node_t*)new node_x_t<47>(((node_x_t<46>*)current)->base.num_elements, ((node_x_t<46>*)current)->chars, ((node_x_t<46>*)current)->children,key));break;
        case 47:return ((node_t*)new node_x_t<48>(((node_x_t<47>*)current)->base.num_elements, ((node_x_t<47>*)current)->chars, ((node_x_t<47>*)current)->children,key));break;
        case 48:return ((node_t*)new node_x_t<49>(((node_x_t<48>*)current)->base.num_elements, ((node_x_t<48>*)current)->chars, ((node_x_t<48>*)current)->children,key));break;
        case 49:return ((node_t*)new node_x_t<50>(((node_x_t<49>*)current)->base.num_elements, ((node_x_t<49>*)current)->chars, ((node_x_t<49>*)current)->children,key));break;
        case 50:return ((node_t*)new node_x_t<51>(((node_x_t<50>*)current)->base.num_elements, ((node_x_t<50>*)current)->chars, ((node_x_t<50>*)current)->children,key));break;
        case 51:return ((node_t*)new node_x_t<52>(((node_x_t<51>*)current)->base.num_elements, ((node_x_t<51>*)current)->chars, ((node_x_t<51>*)current)->children,key));break;
        case 52:return ((node_t*)new node_x_t<53>(((node_x_t<52>*)current)->base.num_elements, ((node_x_t<52>*)current)->chars, ((node_x_t<52>*)current)->children,key));break;
        case 53:return ((node_t*)new node_x_t<54>(((node_x_t<53>*)current)->base.num_elements, ((node_x_t<53>*)current)->chars, ((node_x_t<53>*)current)->children,key));break;
        case 54:return ((node_t*)new node_x_t<55>(((node_x_t<54>*)current)->base.num_elements, ((node_x_t<54>*)current)->chars, ((node_x_t<54>*)current)->children,key));break;
        case 55:return ((node_t*)new node_x_t<56>(((node_x_t<55>*)current)->base.num_elements, ((node_x_t<55>*)current)->chars, ((node_x_t<55>*)current)->children,key));break;
        case 56:return ((node_t*)new node_x_t<57>(((node_x_t<56>*)current)->base.num_elements, ((node_x_t<56>*)current)->chars, ((node_x_t<56>*)current)->children,key));break;
        case 57:return ((node_t*)new node_x_t<58>(((node_x_t<57>*)current)->base.num_elements, ((node_x_t<57>*)current)->chars, ((node_x_t<57>*)current)->children,key));break;
        case 58:return ((node_t*)new node_x_t<59>(((node_x_t<58>*)current)->base.num_elements, ((node_x_t<58>*)current)->chars, ((node_x_t<58>*)current)->children,key));break;
        case 59:return ((node_t*)new node_x_t<60>(((node_x_t<59>*)current)->base.num_elements, ((node_x_t<59>*)current)->chars, ((node_x_t<59>*)current)->children,key));break;
        case 60:return ((node_t*)new node_x_t<61>(((node_x_t<60>*)current)->base.num_elements, ((node_x_t<60>*)current)->chars, ((node_x_t<60>*)current)->children,key));break;
        case 61:return ((node_t*)new node_x_t<62>(((node_x_t<61>*)current)->base.num_elements, ((node_x_t<61>*)current)->chars, ((node_x_t<61>*)current)->children,key));break;
        case 62:return ((node_t*)new node_x_t<63>(((node_x_t<62>*)current)->base.num_elements, ((node_x_t<62>*)current)->chars, ((node_x_t<62>*)current)->children,key));break;
        case 63:return ((node_t*)new node_x_t<64>(((node_x_t<63>*)current)->base.num_elements, ((node_x_t<63>*)current)->chars, ((node_x_t<63>*)current)->children,key));break;
        case 64:return ((node_t*)new node_x_t<65>(((node_x_t<64>*)current)->base.num_elements, ((node_x_t<64>*)current)->chars, ((node_x_t<64>*)current)->children,key));break;
        case 65:return ((node_t*)new node_x_t<66>(((node_x_t<65>*)current)->base.num_elements, ((node_x_t<65>*)current)->chars, ((node_x_t<65>*)current)->children,key));break;
        case 66:return ((node_t*)new node_x_t<67>(((node_x_t<66>*)current)->base.num_elements, ((node_x_t<66>*)current)->chars, ((node_x_t<66>*)current)->children,key));break;
        case 67:return ((node_t*)new node_x_t<68>(((node_x_t<67>*)current)->base.num_elements, ((node_x_t<67>*)current)->chars, ((node_x_t<67>*)current)->children,key));break;
        case 68:return ((node_t*)new node_x_t<69>(((node_x_t<68>*)current)->base.num_elements, ((node_x_t<68>*)current)->chars, ((node_x_t<68>*)current)->children,key));break;
        case 69:return ((node_t*)new node_x_t<70>(((node_x_t<69>*)current)->base.num_elements, ((node_x_t<69>*)current)->chars, ((node_x_t<69>*)current)->children,key));break;
        case 70:return ((node_t*)new node_x_t<71>(((node_x_t<70>*)current)->base.num_elements, ((node_x_t<70>*)current)->chars, ((node_x_t<70>*)current)->children,key));break;
        case 71:return ((node_t*)new node_x_t<72>(((node_x_t<71>*)current)->base.num_elements, ((node_x_t<71>*)current)->chars, ((node_x_t<71>*)current)->children,key));break;
        case 72:return ((node_t*)new node_x_t<73>(((node_x_t<72>*)current)->base.num_elements, ((node_x_t<72>*)current)->chars, ((node_x_t<72>*)current)->children,key));break;
        case 73:return ((node_t*)new node_x_t<74>(((node_x_t<73>*)current)->base.num_elements, ((node_x_t<73>*)current)->chars, ((node_x_t<73>*)current)->children,key));break;
        case 74:return ((node_t*)new node_x_t<75>(((node_x_t<74>*)current)->base.num_elements, ((node_x_t<74>*)current)->chars, ((node_x_t<74>*)current)->children,key));break;
        case 75:return ((node_t*)new node_x_t<76>(((node_x_t<75>*)current)->base.num_elements, ((node_x_t<75>*)current)->chars, ((node_x_t<75>*)current)->children,key));break;
        case 76:return ((node_t*)new node_x_t<77>(((node_x_t<76>*)current)->base.num_elements, ((node_x_t<76>*)current)->chars, ((node_x_t<76>*)current)->children,key));break;
        case 77:return ((node_t*)new node_x_t<78>(((node_x_t<77>*)current)->base.num_elements, ((node_x_t<77>*)current)->chars, ((node_x_t<77>*)current)->children,key));break;
        case 78:return ((node_t*)new node_x_t<79>(((node_x_t<78>*)current)->base.num_elements, ((node_x_t<78>*)current)->chars, ((node_x_t<78>*)current)->children,key));break;
        case 79:return ((node_t*)new node_x_t<80>(((node_x_t<79>*)current)->base.num_elements, ((node_x_t<79>*)current)->chars, ((node_x_t<79>*)current)->children,key));break;
        case 80:return ((node_t*)new node_x_t<81>(((node_x_t<80>*)current)->base.num_elements, ((node_x_t<80>*)current)->chars, ((node_x_t<80>*)current)->children,key));break;
        case 81:return ((node_t*)new node_x_t<82>(((node_x_t<81>*)current)->base.num_elements, ((node_x_t<81>*)current)->chars, ((node_x_t<81>*)current)->children,key));break;
        case 82:return ((node_t*)new node_x_t<83>(((node_x_t<82>*)current)->base.num_elements, ((node_x_t<82>*)current)->chars, ((node_x_t<82>*)current)->children,key));break;
        case 83:return ((node_t*)new node_x_t<84>(((node_x_t<83>*)current)->base.num_elements, ((node_x_t<83>*)current)->chars, ((node_x_t<83>*)current)->children,key));break;
        case 84:return ((node_t*)new node_x_t<85>(((node_x_t<84>*)current)->base.num_elements, ((node_x_t<84>*)current)->chars, ((node_x_t<84>*)current)->children,key));break;
        case 85:return ((node_t*)new node_x_t<86>(((node_x_t<85>*)current)->base.num_elements, ((node_x_t<85>*)current)->chars, ((node_x_t<85>*)current)->children,key));break;
        case 86:return ((node_t*)new node_x_t<87>(((node_x_t<86>*)current)->base.num_elements, ((node_x_t<86>*)current)->chars, ((node_x_t<86>*)current)->children,key));break;
        case 87:return ((node_t*)new node_x_t<88>(((node_x_t<87>*)current)->base.num_elements, ((node_x_t<87>*)current)->chars, ((node_x_t<87>*)current)->children,key));break;
        case 88:return ((node_t*)new node_x_t<89>(((node_x_t<88>*)current)->base.num_elements, ((node_x_t<88>*)current)->chars, ((node_x_t<88>*)current)->children,key));break;
        case 89:return ((node_t*)new node_x_t<90>(((node_x_t<89>*)current)->base.num_elements, ((node_x_t<89>*)current)->chars, ((node_x_t<89>*)current)->children,key));break;
        case 90:return ((node_t*)new node_x_t<91>(((node_x_t<90>*)current)->base.num_elements, ((node_x_t<90>*)current)->chars, ((node_x_t<90>*)current)->children,key));break;
        case 91:return ((node_t*)new node_x_t<92>(((node_x_t<91>*)current)->base.num_elements, ((node_x_t<91>*)current)->chars, ((node_x_t<91>*)current)->children,key));break;
        case 92:return ((node_t*)new node_x_t<93>(((node_x_t<92>*)current)->base.num_elements, ((node_x_t<92>*)current)->chars, ((node_x_t<92>*)current)->children,key));break;
        case 93:return ((node_t*)new node_x_t<94>(((node_x_t<93>*)current)->base.num_elements, ((node_x_t<93>*)current)->chars, ((node_x_t<93>*)current)->children,key));break;
        case 94:return ((node_t*)new node_x_t<95>(((node_x_t<94>*)current)->base.num_elements, ((node_x_t<94>*)current)->chars, ((node_x_t<94>*)current)->children,key));break;
        case 95:return ((node_t*)new node_x_t<96>(((node_x_t<95>*)current)->base.num_elements, ((node_x_t<95>*)current)->chars, ((node_x_t<95>*)current)->children,key));break;
        case 96:return ((node_t*)new node_x_t<97>(((node_x_t<96>*)current)->base.num_elements, ((node_x_t<96>*)current)->chars, ((node_x_t<96>*)current)->children,key));break;
        case 97:return ((node_t*)new node_x_t<98>(((node_x_t<97>*)current)->base.num_elements, ((node_x_t<97>*)current)->chars, ((node_x_t<97>*)current)->children,key));break;
        case 98:return ((node_t*)new node_x_t<99>(((node_x_t<98>*)current)->base.num_elements, ((node_x_t<98>*)current)->chars, ((node_x_t<98>*)current)->children,key));break;
        case 99:return ((node_t*)new node_x_t<100>(((node_x_t<99>*)current)->base.num_elements, ((node_x_t<99>*)current)->chars, ((node_x_t<99>*)current)->children,key));break;
        case 100:return ((node_t*)new node_x_t<101>(((node_x_t<100>*)current)->base.num_elements, ((node_x_t<100>*)current)->chars, ((node_x_t<100>*)current)->children,key));break;
        case 101:return ((node_t*)new node_x_t<102>(((node_x_t<101>*)current)->base.num_elements, ((node_x_t<101>*)current)->chars, ((node_x_t<101>*)current)->children,key));break;
        case 102:return ((node_t*)new node_x_t<103>(((node_x_t<102>*)current)->base.num_elements, ((node_x_t<102>*)current)->chars, ((node_x_t<102>*)current)->children,key));break;
        case 103:return ((node_t*)new node_x_t<104>(((node_x_t<103>*)current)->base.num_elements, ((node_x_t<103>*)current)->chars, ((node_x_t<103>*)current)->children,key));break;
        case 104:return ((node_t*)new node_x_t<105>(((node_x_t<104>*)current)->base.num_elements, ((node_x_t<104>*)current)->chars, ((node_x_t<104>*)current)->children,key));break;
        case 105:return ((node_t*)new node_x_t<106>(((node_x_t<105>*)current)->base.num_elements, ((node_x_t<105>*)current)->chars, ((node_x_t<105>*)current)->children,key));break;
        case 106:return ((node_t*)new node_x_t<107>(((node_x_t<106>*)current)->base.num_elements, ((node_x_t<106>*)current)->chars, ((node_x_t<106>*)current)->children,key));break;
        case 107:return ((node_t*)new node_x_t<108>(((node_x_t<107>*)current)->base.num_elements, ((node_x_t<107>*)current)->chars, ((node_x_t<107>*)current)->children,key));break;
        case 108:return ((node_t*)new node_x_t<109>(((node_x_t<108>*)current)->base.num_elements, ((node_x_t<108>*)current)->chars, ((node_x_t<108>*)current)->children,key));break;
        case 109:return ((node_t*)new node_x_t<110>(((node_x_t<109>*)current)->base.num_elements, ((node_x_t<109>*)current)->chars, ((node_x_t<109>*)current)->children,key));break;
        case 110:return ((node_t*)new node_x_t<111>(((node_x_t<110>*)current)->base.num_elements, ((node_x_t<110>*)current)->chars, ((node_x_t<110>*)current)->children,key));break;
        case 111:return ((node_t*)new node_x_t<112>(((node_x_t<111>*)current)->base.num_elements, ((node_x_t<111>*)current)->chars, ((node_x_t<111>*)current)->children,key));break;
        case 112:return ((node_t*)new node_x_t<113>(((node_x_t<112>*)current)->base.num_elements, ((node_x_t<112>*)current)->chars, ((node_x_t<112>*)current)->children,key));break;
        case 113:return ((node_t*)new node_x_t<114>(((node_x_t<113>*)current)->base.num_elements, ((node_x_t<113>*)current)->chars, ((node_x_t<113>*)current)->children,key));break;
        case 114:return ((node_t*)new node_x_t<115>(((node_x_t<114>*)current)->base.num_elements, ((node_x_t<114>*)current)->chars, ((node_x_t<114>*)current)->children,key));break;
        case 115:return ((node_t*)new node_x_t<116>(((node_x_t<115>*)current)->base.num_elements, ((node_x_t<115>*)current)->chars, ((node_x_t<115>*)current)->children,key));break;
        case 116:return ((node_t*)new node_x_t<117>(((node_x_t<116>*)current)->base.num_elements, ((node_x_t<116>*)current)->chars, ((node_x_t<116>*)current)->children,key));break;
        case 117:return ((node_t*)new node_x_t<118>(((node_x_t<117>*)current)->base.num_elements, ((node_x_t<117>*)current)->chars, ((node_x_t<117>*)current)->children,key));break;
        case 118:return ((node_t*)new node_x_t<119>(((node_x_t<118>*)current)->base.num_elements, ((node_x_t<118>*)current)->chars, ((node_x_t<118>*)current)->children,key));break;
        case 119:return ((node_t*)new node_x_t<120>(((node_x_t<119>*)current)->base.num_elements, ((node_x_t<119>*)current)->chars, ((node_x_t<119>*)current)->children,key));break;
        case 120:return ((node_t*)new node_x_t<121>(((node_x_t<120>*)current)->base.num_elements, ((node_x_t<120>*)current)->chars, ((node_x_t<120>*)current)->children,key));break;
        case 121:return ((node_t*)new node_x_t<122>(((node_x_t<121>*)current)->base.num_elements, ((node_x_t<121>*)current)->chars, ((node_x_t<121>*)current)->children,key));break;
        case 122:return ((node_t*)new node_x_t<123>(((node_x_t<122>*)current)->base.num_elements, ((node_x_t<122>*)current)->chars, ((node_x_t<122>*)current)->children,key));break;
        case 123:return ((node_t*)new node_x_t<124>(((node_x_t<123>*)current)->base.num_elements, ((node_x_t<123>*)current)->chars, ((node_x_t<123>*)current)->children,key));break;
        case 124:return ((node_t*)new node_x_t<125>(((node_x_t<124>*)current)->base.num_elements, ((node_x_t<124>*)current)->chars, ((node_x_t<124>*)current)->children,key));break;
        case 125:return ((node_t*)new node_x_t<126>(((node_x_t<125>*)current)->base.num_elements, ((node_x_t<125>*)current)->chars, ((node_x_t<125>*)current)->children,key));break;
        case 126:return ((node_t*)new node_x_t<127>(((node_x_t<126>*)current)->base.num_elements, ((node_x_t<126>*)current)->chars, ((node_x_t<126>*)current)->children,key));break;
        case 127:return ((node_t*)new node_x_t<128>(((node_x_t<127>*)current)->base.num_elements, ((node_x_t<127>*)current)->chars, ((node_x_t<127>*)current)->children,key));break;
        case 128:return ((node_t*)new node_x_t<129>(((node_x_t<128>*)current)->base.num_elements, ((node_x_t<128>*)current)->chars, ((node_x_t<128>*)current)->children,key));break;
        case 129:return ((node_t*)new node_x_t<130>(((node_x_t<129>*)current)->base.num_elements, ((node_x_t<129>*)current)->chars, ((node_x_t<129>*)current)->children,key));break;
        case 130:return ((node_t*)new node_x_t<131>(((node_x_t<130>*)current)->base.num_elements, ((node_x_t<130>*)current)->chars, ((node_x_t<130>*)current)->children,key));break;
        case 131:return ((node_t*)new node_x_t<132>(((node_x_t<131>*)current)->base.num_elements, ((node_x_t<131>*)current)->chars, ((node_x_t<131>*)current)->children,key));break;
        case 132:return ((node_t*)new node_x_t<133>(((node_x_t<132>*)current)->base.num_elements, ((node_x_t<132>*)current)->chars, ((node_x_t<132>*)current)->children,key));break;
        case 133:return ((node_t*)new node_x_t<134>(((node_x_t<133>*)current)->base.num_elements, ((node_x_t<133>*)current)->chars, ((node_x_t<133>*)current)->children,key));break;
        case 134:return ((node_t*)new node_x_t<135>(((node_x_t<134>*)current)->base.num_elements, ((node_x_t<134>*)current)->chars, ((node_x_t<134>*)current)->children,key));break;
        case 135:return ((node_t*)new node_x_t<136>(((node_x_t<135>*)current)->base.num_elements, ((node_x_t<135>*)current)->chars, ((node_x_t<135>*)current)->children,key));break;
        case 136:return ((node_t*)new node_x_t<137>(((node_x_t<136>*)current)->base.num_elements, ((node_x_t<136>*)current)->chars, ((node_x_t<136>*)current)->children,key));break;
        case 137:return ((node_t*)new node_x_t<138>(((node_x_t<137>*)current)->base.num_elements, ((node_x_t<137>*)current)->chars, ((node_x_t<137>*)current)->children,key));break;
        case 138:return ((node_t*)new node_x_t<139>(((node_x_t<138>*)current)->base.num_elements, ((node_x_t<138>*)current)->chars, ((node_x_t<138>*)current)->children,key));break;
        case 139:return ((node_t*)new node_x_t<140>(((node_x_t<139>*)current)->base.num_elements, ((node_x_t<139>*)current)->chars, ((node_x_t<139>*)current)->children,key));break;
        case 140:return ((node_t*)new node_x_t<141>(((node_x_t<140>*)current)->base.num_elements, ((node_x_t<140>*)current)->chars, ((node_x_t<140>*)current)->children,key));break;
        case 141:return ((node_t*)new node_x_t<142>(((node_x_t<141>*)current)->base.num_elements, ((node_x_t<141>*)current)->chars, ((node_x_t<141>*)current)->children,key));break;
        case 142:return ((node_t*)new node_x_t<143>(((node_x_t<142>*)current)->base.num_elements, ((node_x_t<142>*)current)->chars, ((node_x_t<142>*)current)->children,key));break;
        case 143:return ((node_t*)new node_x_t<144>(((node_x_t<143>*)current)->base.num_elements, ((node_x_t<143>*)current)->chars, ((node_x_t<143>*)current)->children,key));break;
        case 144:return ((node_t*)new node_x_t<145>(((node_x_t<144>*)current)->base.num_elements, ((node_x_t<144>*)current)->chars, ((node_x_t<144>*)current)->children,key));break;
        case 145:return ((node_t*)new node_x_t<146>(((node_x_t<145>*)current)->base.num_elements, ((node_x_t<145>*)current)->chars, ((node_x_t<145>*)current)->children,key));break;
        case 146:return ((node_t*)new node_x_t<147>(((node_x_t<146>*)current)->base.num_elements, ((node_x_t<146>*)current)->chars, ((node_x_t<146>*)current)->children,key));break;
        case 147:return ((node_t*)new node_x_t<148>(((node_x_t<147>*)current)->base.num_elements, ((node_x_t<147>*)current)->chars, ((node_x_t<147>*)current)->children,key));break;
        case 148:return ((node_t*)new node_x_t<149>(((node_x_t<148>*)current)->base.num_elements, ((node_x_t<148>*)current)->chars, ((node_x_t<148>*)current)->children,key));break;
        case 149:return ((node_t*)new node_x_t<150>(((node_x_t<149>*)current)->base.num_elements, ((node_x_t<149>*)current)->chars, ((node_x_t<149>*)current)->children,key));break;
        case 150:return ((node_t*)new node_x_t<151>(((node_x_t<150>*)current)->base.num_elements, ((node_x_t<150>*)current)->chars, ((node_x_t<150>*)current)->children,key));break;
        case 151:return ((node_t*)new node_x_t<152>(((node_x_t<151>*)current)->base.num_elements, ((node_x_t<151>*)current)->chars, ((node_x_t<151>*)current)->children,key));break;
        case 152:return ((node_t*)new node_x_t<153>(((node_x_t<152>*)current)->base.num_elements, ((node_x_t<152>*)current)->chars, ((node_x_t<152>*)current)->children,key));break;
        case 153:return ((node_t*)new node_x_t<154>(((node_x_t<153>*)current)->base.num_elements, ((node_x_t<153>*)current)->chars, ((node_x_t<153>*)current)->children,key));break;
        case 154:return ((node_t*)new node_x_t<155>(((node_x_t<154>*)current)->base.num_elements, ((node_x_t<154>*)current)->chars, ((node_x_t<154>*)current)->children,key));break;
        case 155:return ((node_t*)new node_x_t<156>(((node_x_t<155>*)current)->base.num_elements, ((node_x_t<155>*)current)->chars, ((node_x_t<155>*)current)->children,key));break;
        case 156:return ((node_t*)new node_x_t<157>(((node_x_t<156>*)current)->base.num_elements, ((node_x_t<156>*)current)->chars, ((node_x_t<156>*)current)->children,key));break;
        case 157:return ((node_t*)new node_x_t<158>(((node_x_t<157>*)current)->base.num_elements, ((node_x_t<157>*)current)->chars, ((node_x_t<157>*)current)->children,key));break;
        case 158:return ((node_t*)new node_x_t<159>(((node_x_t<158>*)current)->base.num_elements, ((node_x_t<158>*)current)->chars, ((node_x_t<158>*)current)->children,key));break;
        case 159:return ((node_t*)new node_x_t<160>(((node_x_t<159>*)current)->base.num_elements, ((node_x_t<159>*)current)->chars, ((node_x_t<159>*)current)->children,key));break;
        case 160:return ((node_t*)new node_x_t<161>(((node_x_t<160>*)current)->base.num_elements, ((node_x_t<160>*)current)->chars, ((node_x_t<160>*)current)->children,key));break;
        case 161:return ((node_t*)new node_x_t<162>(((node_x_t<161>*)current)->base.num_elements, ((node_x_t<161>*)current)->chars, ((node_x_t<161>*)current)->children,key));break;
        case 162:return ((node_t*)new node_x_t<163>(((node_x_t<162>*)current)->base.num_elements, ((node_x_t<162>*)current)->chars, ((node_x_t<162>*)current)->children,key));break;
        case 163:return ((node_t*)new node_x_t<164>(((node_x_t<163>*)current)->base.num_elements, ((node_x_t<163>*)current)->chars, ((node_x_t<163>*)current)->children,key));break;
        case 164:return ((node_t*)new node_x_t<165>(((node_x_t<164>*)current)->base.num_elements, ((node_x_t<164>*)current)->chars, ((node_x_t<164>*)current)->children,key));break;
        case 165:return ((node_t*)new node_x_t<166>(((node_x_t<165>*)current)->base.num_elements, ((node_x_t<165>*)current)->chars, ((node_x_t<165>*)current)->children,key));break;
        case 166:return ((node_t*)new node_x_t<167>(((node_x_t<166>*)current)->base.num_elements, ((node_x_t<166>*)current)->chars, ((node_x_t<166>*)current)->children,key));break;
        case 167:return ((node_t*)new node_x_t<168>(((node_x_t<167>*)current)->base.num_elements, ((node_x_t<167>*)current)->chars, ((node_x_t<167>*)current)->children,key));break;
        case 168:return ((node_t*)new node_x_t<169>(((node_x_t<168>*)current)->base.num_elements, ((node_x_t<168>*)current)->chars, ((node_x_t<168>*)current)->children,key));break;
        case 169:return ((node_t*)new node_x_t<170>(((node_x_t<169>*)current)->base.num_elements, ((node_x_t<169>*)current)->chars, ((node_x_t<169>*)current)->children,key));break;
        case 170:return ((node_t*)new node_x_t<171>(((node_x_t<170>*)current)->base.num_elements, ((node_x_t<170>*)current)->chars, ((node_x_t<170>*)current)->children,key));break;
        case 171:return ((node_t*)new node_x_t<172>(((node_x_t<171>*)current)->base.num_elements, ((node_x_t<171>*)current)->chars, ((node_x_t<171>*)current)->children,key));break;
        case 172:return ((node_t*)new node_x_t<173>(((node_x_t<172>*)current)->base.num_elements, ((node_x_t<172>*)current)->chars, ((node_x_t<172>*)current)->children,key));break;
        case 173:return ((node_t*)new node_x_t<174>(((node_x_t<173>*)current)->base.num_elements, ((node_x_t<173>*)current)->chars, ((node_x_t<173>*)current)->children,key));break;
        case 174:return ((node_t*)new node_x_t<175>(((node_x_t<174>*)current)->base.num_elements, ((node_x_t<174>*)current)->chars, ((node_x_t<174>*)current)->children,key));break;
        case 175:return ((node_t*)new node_x_t<176>(((node_x_t<175>*)current)->base.num_elements, ((node_x_t<175>*)current)->chars, ((node_x_t<175>*)current)->children,key));break;
        case 176:return ((node_t*)new node_x_t<177>(((node_x_t<176>*)current)->base.num_elements, ((node_x_t<176>*)current)->chars, ((node_x_t<176>*)current)->children,key));break;
        case 177:return ((node_t*)new node_x_t<178>(((node_x_t<177>*)current)->base.num_elements, ((node_x_t<177>*)current)->chars, ((node_x_t<177>*)current)->children,key));break;
        case 178:return ((node_t*)new node_x_t<179>(((node_x_t<178>*)current)->base.num_elements, ((node_x_t<178>*)current)->chars, ((node_x_t<178>*)current)->children,key));break;
        case 179:return ((node_t*)new node_x_t<180>(((node_x_t<179>*)current)->base.num_elements, ((node_x_t<179>*)current)->chars, ((node_x_t<179>*)current)->children,key));break;
        case 180:return ((node_t*)new node_x_t<181>(((node_x_t<180>*)current)->base.num_elements, ((node_x_t<180>*)current)->chars, ((node_x_t<180>*)current)->children,key));break;
        case 181:return ((node_t*)new node_x_t<182>(((node_x_t<181>*)current)->base.num_elements, ((node_x_t<181>*)current)->chars, ((node_x_t<181>*)current)->children,key));break;
        case 182:return ((node_t*)new node_x_t<183>(((node_x_t<182>*)current)->base.num_elements, ((node_x_t<182>*)current)->chars, ((node_x_t<182>*)current)->children,key));break;
        case 183:return ((node_t*)new node_x_t<184>(((node_x_t<183>*)current)->base.num_elements, ((node_x_t<183>*)current)->chars, ((node_x_t<183>*)current)->children,key));break;
        case 184:return ((node_t*)new node_x_t<185>(((node_x_t<184>*)current)->base.num_elements, ((node_x_t<184>*)current)->chars, ((node_x_t<184>*)current)->children,key));break;
        case 185:return ((node_t*)new node_x_t<186>(((node_x_t<185>*)current)->base.num_elements, ((node_x_t<185>*)current)->chars, ((node_x_t<185>*)current)->children,key));break;
        case 186:return ((node_t*)new node_x_t<187>(((node_x_t<186>*)current)->base.num_elements, ((node_x_t<186>*)current)->chars, ((node_x_t<186>*)current)->children,key));break;
        case 187:return ((node_t*)new node_x_t<188>(((node_x_t<187>*)current)->base.num_elements, ((node_x_t<187>*)current)->chars, ((node_x_t<187>*)current)->children,key));break;
        case 188:return ((node_t*)new node_x_t<189>(((node_x_t<188>*)current)->base.num_elements, ((node_x_t<188>*)current)->chars, ((node_x_t<188>*)current)->children,key));break;
        case 189:return ((node_t*)new node_x_t<190>(((node_x_t<189>*)current)->base.num_elements, ((node_x_t<189>*)current)->chars, ((node_x_t<189>*)current)->children,key));break;
        case 190:return ((node_t*)new node_x_t<191>(((node_x_t<190>*)current)->base.num_elements, ((node_x_t<190>*)current)->chars, ((node_x_t<190>*)current)->children,key));break;
        case 191:return ((node_t*)new node_x_t<192>(((node_x_t<191>*)current)->base.num_elements, ((node_x_t<191>*)current)->chars, ((node_x_t<191>*)current)->children,key));break;
        case 192:return ((node_t*)new node_x_t<193>(((node_x_t<192>*)current)->base.num_elements, ((node_x_t<192>*)current)->chars, ((node_x_t<192>*)current)->children,key));break;
        case 193:return ((node_t*)new node_x_t<194>(((node_x_t<193>*)current)->base.num_elements, ((node_x_t<193>*)current)->chars, ((node_x_t<193>*)current)->children,key));break;
        case 194:return ((node_t*)new node_x_t<195>(((node_x_t<194>*)current)->base.num_elements, ((node_x_t<194>*)current)->chars, ((node_x_t<194>*)current)->children,key));break;
        case 195:return ((node_t*)new node_x_t<196>(((node_x_t<195>*)current)->base.num_elements, ((node_x_t<195>*)current)->chars, ((node_x_t<195>*)current)->children,key));break;
        case 196:return ((node_t*)new node_x_t<197>(((node_x_t<196>*)current)->base.num_elements, ((node_x_t<196>*)current)->chars, ((node_x_t<196>*)current)->children,key));break;
        case 197:return ((node_t*)new node_x_t<198>(((node_x_t<197>*)current)->base.num_elements, ((node_x_t<197>*)current)->chars, ((node_x_t<197>*)current)->children,key));break;
        case 198:return ((node_t*)new node_x_t<199>(((node_x_t<198>*)current)->base.num_elements, ((node_x_t<198>*)current)->chars, ((node_x_t<198>*)current)->children,key));break;
        case 199:return ((node_t*)new node_x_t<200>(((node_x_t<199>*)current)->base.num_elements, ((node_x_t<199>*)current)->chars, ((node_x_t<199>*)current)->children,key));break;
        case 200:return ((node_t*)new node_x_t<201>(((node_x_t<200>*)current)->base.num_elements, ((node_x_t<200>*)current)->chars, ((node_x_t<200>*)current)->children,key));break;
        case 201:return ((node_t*)new node_x_t<202>(((node_x_t<201>*)current)->base.num_elements, ((node_x_t<201>*)current)->chars, ((node_x_t<201>*)current)->children,key));break;
        case 202:return ((node_t*)new node_x_t<203>(((node_x_t<202>*)current)->base.num_elements, ((node_x_t<202>*)current)->chars, ((node_x_t<202>*)current)->children,key));break;
        case 203:return ((node_t*)new node_x_t<204>(((node_x_t<203>*)current)->base.num_elements, ((node_x_t<203>*)current)->chars, ((node_x_t<203>*)current)->children,key));break;
        case 204:return ((node_t*)new node_x_t<205>(((node_x_t<204>*)current)->base.num_elements, ((node_x_t<204>*)current)->chars, ((node_x_t<204>*)current)->children,key));break;
        case 205:return ((node_t*)new node_x_t<206>(((node_x_t<205>*)current)->base.num_elements, ((node_x_t<205>*)current)->chars, ((node_x_t<205>*)current)->children,key));break;
        case 206:return ((node_t*)new node_x_t<207>(((node_x_t<206>*)current)->base.num_elements, ((node_x_t<206>*)current)->chars, ((node_x_t<206>*)current)->children,key));break;
        case 207:return ((node_t*)new node_x_t<208>(((node_x_t<207>*)current)->base.num_elements, ((node_x_t<207>*)current)->chars, ((node_x_t<207>*)current)->children,key));break;
        case 208:return ((node_t*)new node_x_t<209>(((node_x_t<208>*)current)->base.num_elements, ((node_x_t<208>*)current)->chars, ((node_x_t<208>*)current)->children,key));break;
        case 209:return ((node_t*)new node_x_t<210>(((node_x_t<209>*)current)->base.num_elements, ((node_x_t<209>*)current)->chars, ((node_x_t<209>*)current)->children,key));break;
        case 210:return ((node_t*)new node_x_t<211>(((node_x_t<210>*)current)->base.num_elements, ((node_x_t<210>*)current)->chars, ((node_x_t<210>*)current)->children,key));break;
        case 211:return ((node_t*)new node_x_t<212>(((node_x_t<211>*)current)->base.num_elements, ((node_x_t<211>*)current)->chars, ((node_x_t<211>*)current)->children,key));break;
        case 212:return ((node_t*)new node_x_t<213>(((node_x_t<212>*)current)->base.num_elements, ((node_x_t<212>*)current)->chars, ((node_x_t<212>*)current)->children,key));break;
        case 213:return ((node_t*)new node_x_t<214>(((node_x_t<213>*)current)->base.num_elements, ((node_x_t<213>*)current)->chars, ((node_x_t<213>*)current)->children,key));break;
        case 214:return ((node_t*)new node_x_t<215>(((node_x_t<214>*)current)->base.num_elements, ((node_x_t<214>*)current)->chars, ((node_x_t<214>*)current)->children,key));break;
        case 215:return ((node_t*)new node_x_t<216>(((node_x_t<215>*)current)->base.num_elements, ((node_x_t<215>*)current)->chars, ((node_x_t<215>*)current)->children,key));break;
        case 216:return ((node_t*)new node_x_t<217>(((node_x_t<216>*)current)->base.num_elements, ((node_x_t<216>*)current)->chars, ((node_x_t<216>*)current)->children,key));break;
        case 217:return ((node_t*)new node_x_t<218>(((node_x_t<217>*)current)->base.num_elements, ((node_x_t<217>*)current)->chars, ((node_x_t<217>*)current)->children,key));break;
        case 218:return ((node_t*)new node_x_t<219>(((node_x_t<218>*)current)->base.num_elements, ((node_x_t<218>*)current)->chars, ((node_x_t<218>*)current)->children,key));break;
        case 219:return ((node_t*)new node_x_t<220>(((node_x_t<219>*)current)->base.num_elements, ((node_x_t<219>*)current)->chars, ((node_x_t<219>*)current)->children,key));break;
        case 220:return ((node_t*)new node_x_t<221>(((node_x_t<220>*)current)->base.num_elements, ((node_x_t<220>*)current)->chars, ((node_x_t<220>*)current)->children,key));break;
        case 221:return ((node_t*)new node_x_t<222>(((node_x_t<221>*)current)->base.num_elements, ((node_x_t<221>*)current)->chars, ((node_x_t<221>*)current)->children,key));break;
        case 222:return ((node_t*)new node_x_t<223>(((node_x_t<222>*)current)->base.num_elements, ((node_x_t<222>*)current)->chars, ((node_x_t<222>*)current)->children,key));break;
        case 223:return ((node_t*)new node_x_t<224>(((node_x_t<223>*)current)->base.num_elements, ((node_x_t<223>*)current)->chars, ((node_x_t<223>*)current)->children,key));break;
        case 224:return ((node_t*)new node_x_t<225>(((node_x_t<224>*)current)->base.num_elements, ((node_x_t<224>*)current)->chars, ((node_x_t<224>*)current)->children,key));break;
        case 225:return ((node_t*)new node_x_t<226>(((node_x_t<225>*)current)->base.num_elements, ((node_x_t<225>*)current)->chars, ((node_x_t<225>*)current)->children,key));break;
        case 226:return ((node_t*)new node_x_t<227>(((node_x_t<226>*)current)->base.num_elements, ((node_x_t<226>*)current)->chars, ((node_x_t<226>*)current)->children,key));break;
        case 227:return ((node_t*)new node_x_t<228>(((node_x_t<227>*)current)->base.num_elements, ((node_x_t<227>*)current)->chars, ((node_x_t<227>*)current)->children,key));break;
        case 228:return ((node_t*)new node_x_t<229>(((node_x_t<228>*)current)->base.num_elements, ((node_x_t<228>*)current)->chars, ((node_x_t<228>*)current)->children,key));break;
        case 229:return ((node_t*)new node_x_t<230>(((node_x_t<229>*)current)->base.num_elements, ((node_x_t<229>*)current)->chars, ((node_x_t<229>*)current)->children,key));break;
        case 230:return ((node_t*)new node_x_t<231>(((node_x_t<230>*)current)->base.num_elements, ((node_x_t<230>*)current)->chars, ((node_x_t<230>*)current)->children,key));break;
        case 231:return ((node_t*)new node_x_t<232>(((node_x_t<231>*)current)->base.num_elements, ((node_x_t<231>*)current)->chars, ((node_x_t<231>*)current)->children,key));break;
        case 232:return ((node_t*)new node_x_t<233>(((node_x_t<232>*)current)->base.num_elements, ((node_x_t<232>*)current)->chars, ((node_x_t<232>*)current)->children,key));break;
        case 233:return ((node_t*)new node_x_t<234>(((node_x_t<233>*)current)->base.num_elements, ((node_x_t<233>*)current)->chars, ((node_x_t<233>*)current)->children,key));break;
        case 234:return ((node_t*)new node_x_t<235>(((node_x_t<234>*)current)->base.num_elements, ((node_x_t<234>*)current)->chars, ((node_x_t<234>*)current)->children,key));break;
        case 235:return ((node_t*)new node_x_t<236>(((node_x_t<235>*)current)->base.num_elements, ((node_x_t<235>*)current)->chars, ((node_x_t<235>*)current)->children,key));break;
        case 236:return ((node_t*)new node_x_t<237>(((node_x_t<236>*)current)->base.num_elements, ((node_x_t<236>*)current)->chars, ((node_x_t<236>*)current)->children,key));break;
        case 237:return ((node_t*)new node_x_t<238>(((node_x_t<237>*)current)->base.num_elements, ((node_x_t<237>*)current)->chars, ((node_x_t<237>*)current)->children,key));break;
        case 238:return ((node_t*)new node_x_t<239>(((node_x_t<238>*)current)->base.num_elements, ((node_x_t<238>*)current)->chars, ((node_x_t<238>*)current)->children,key));break;
        case 239:return ((node_t*)new node_x_t<240>(((node_x_t<239>*)current)->base.num_elements, ((node_x_t<239>*)current)->chars, ((node_x_t<239>*)current)->children,key));break;
        case 240:return ((node_t*)new node_x_t<241>(((node_x_t<240>*)current)->base.num_elements, ((node_x_t<240>*)current)->chars, ((node_x_t<240>*)current)->children,key));break;
        case 241:return ((node_t*)new node_x_t<242>(((node_x_t<241>*)current)->base.num_elements, ((node_x_t<241>*)current)->chars, ((node_x_t<241>*)current)->children,key));break;
        case 242:return ((node_t*)new node_x_t<243>(((node_x_t<242>*)current)->base.num_elements, ((node_x_t<242>*)current)->chars, ((node_x_t<242>*)current)->children,key));break;
        case 243:return ((node_t*)new node_x_t<244>(((node_x_t<243>*)current)->base.num_elements, ((node_x_t<243>*)current)->chars, ((node_x_t<243>*)current)->children,key));break;
        case 244:return ((node_t*)new node_x_t<245>(((node_x_t<244>*)current)->base.num_elements, ((node_x_t<244>*)current)->chars, ((node_x_t<244>*)current)->children,key));break;
        case 245:return ((node_t*)new node_x_t<246>(((node_x_t<245>*)current)->base.num_elements, ((node_x_t<245>*)current)->chars, ((node_x_t<245>*)current)->children,key));break;
        case 246:return ((node_t*)new node_x_t<247>(((node_x_t<246>*)current)->base.num_elements, ((node_x_t<246>*)current)->chars, ((node_x_t<246>*)current)->children,key));break;
        case 247:return ((node_t*)new node_x_t<248>(((node_x_t<247>*)current)->base.num_elements, ((node_x_t<247>*)current)->chars, ((node_x_t<247>*)current)->children,key));break;
        case 248:return ((node_t*)new node_x_t<249>(((node_x_t<248>*)current)->base.num_elements, ((node_x_t<248>*)current)->chars, ((node_x_t<248>*)current)->children,key));break;
        case 249:return ((node_t*)new node_x_t<250>(((node_x_t<249>*)current)->base.num_elements, ((node_x_t<249>*)current)->chars, ((node_x_t<249>*)current)->children,key));break;
        case 250:return ((node_t*)new node_x_t<251>(((node_x_t<250>*)current)->base.num_elements, ((node_x_t<250>*)current)->chars, ((node_x_t<250>*)current)->children,key));break;
        case 251:return ((node_t*)new node_x_t<252>(((node_x_t<251>*)current)->base.num_elements, ((node_x_t<251>*)current)->chars, ((node_x_t<251>*)current)->children,key));break;
        case 252:return ((node_t*)new node_x_t<253>(((node_x_t<252>*)current)->base.num_elements, ((node_x_t<252>*)current)->chars, ((node_x_t<252>*)current)->children,key));break;
        case 253:return ((node_t*)new node_x_t<254>(((node_x_t<253>*)current)->base.num_elements, ((node_x_t<253>*)current)->chars, ((node_x_t<253>*)current)->children,key));break;
        case 254:return ((node_t*)new node_x_t<255>(((node_x_t<254>*)current)->base.num_elements, ((node_x_t<254>*)current)->chars, ((node_x_t<254>*)current)->children,key));break;
        case 255:return ((node_t*)new node_x_t<256>(((node_x_t<255>*)current)->base.num_elements, ((node_x_t<255>*)current)->chars, ((node_x_t<255>*)current)->children,key));break;
    }
    return NULL;
}


node_t* setObjectUtil(int index, node_t* nav){
    switch(nav->num_elements) {
        case 1: return ((node_x_t<1>*)nav)->setObject(index, nav);break;
        case 2: return ((node_x_t<2>*)nav)->setObject(index, nav);break;
        case 3: return ((node_x_t<3>*)nav)->setObject(index, nav);break;
        case 4: return ((node_x_t<4>*)nav)->setObject(index, nav);break;
        case 5: return ((node_x_t<5>*)nav)->setObject(index, nav);break;
        case 6: return ((node_x_t<6>*)nav)->setObject(index, nav);break;
        case 7: return ((node_x_t<7>*)nav)->setObject(index, nav);break;
        case 8: return ((node_x_t<8>*)nav)->setObject(index, nav);break;
        case 9: return ((node_x_t<9>*)nav)->setObject(index, nav);break;
        case 10: return ((node_x_t<10>*)nav)->setObject(index, nav);break;
        case 11: return ((node_x_t<11>*)nav)->setObject(index, nav);break;
        case 12: return ((node_x_t<12>*)nav)->setObject(index, nav);break;
        case 13: return ((node_x_t<13>*)nav)->setObject(index, nav);break;
        case 14: return ((node_x_t<14>*)nav)->setObject(index, nav);break;
        case 15: return ((node_x_t<15>*)nav)->setObject(index, nav);break;
        case 16: return ((node_x_t<16>*)nav)->setObject(index, nav);break;
        case 17: return ((node_x_t<17>*)nav)->setObject(index, nav);break;
        case 18: return ((node_x_t<18>*)nav)->setObject(index, nav);break;
        case 19: return ((node_x_t<19>*)nav)->setObject(index, nav);break;
        case 20: return ((node_x_t<20>*)nav)->setObject(index, nav);break;
        case 21: return ((node_x_t<21>*)nav)->setObject(index, nav);break;
        case 22: return ((node_x_t<22>*)nav)->setObject(index, nav);break;
        case 23: return ((node_x_t<23>*)nav)->setObject(index, nav);break;
        case 24: return ((node_x_t<24>*)nav)->setObject(index, nav);break;
        case 25: return ((node_x_t<25>*)nav)->setObject(index, nav);break;
        case 26: return ((node_x_t<26>*)nav)->setObject(index, nav);break;
        case 27: return ((node_x_t<27>*)nav)->setObject(index, nav);break;
        case 28: return ((node_x_t<28>*)nav)->setObject(index, nav);break;
        case 29: return ((node_x_t<29>*)nav)->setObject(index, nav);break;
        case 30: return ((node_x_t<30>*)nav)->setObject(index, nav);break;
        case 31: return ((node_x_t<31>*)nav)->setObject(index, nav);break;
        case 32: return ((node_x_t<32>*)nav)->setObject(index, nav);break;
        case 33: return ((node_x_t<33>*)nav)->setObject(index, nav);break;
        case 34: return ((node_x_t<34>*)nav)->setObject(index, nav);break;
        case 35: return ((node_x_t<35>*)nav)->setObject(index, nav);break;
        case 36: return ((node_x_t<36>*)nav)->setObject(index, nav);break;
        case 37: return ((node_x_t<37>*)nav)->setObject(index, nav);break;
        case 38: return ((node_x_t<38>*)nav)->setObject(index, nav);break;
        case 39: return ((node_x_t<39>*)nav)->setObject(index, nav);break;
        case 40: return ((node_x_t<40>*)nav)->setObject(index, nav);break;
        case 41: return ((node_x_t<41>*)nav)->setObject(index, nav);break;
        case 42: return ((node_x_t<42>*)nav)->setObject(index, nav);break;
        case 43: return ((node_x_t<43>*)nav)->setObject(index, nav);break;
        case 44: return ((node_x_t<44>*)nav)->setObject(index, nav);break;
        case 45: return ((node_x_t<45>*)nav)->setObject(index, nav);break;
        case 46: return ((node_x_t<46>*)nav)->setObject(index, nav);break;
        case 47: return ((node_x_t<47>*)nav)->setObject(index, nav);break;
        case 48: return ((node_x_t<48>*)nav)->setObject(index, nav);break;
        case 49: return ((node_x_t<49>*)nav)->setObject(index, nav);break;
        case 50: return ((node_x_t<50>*)nav)->setObject(index, nav);break;
        case 51: return ((node_x_t<51>*)nav)->setObject(index, nav);break;
        case 52: return ((node_x_t<52>*)nav)->setObject(index, nav);break;
        case 53: return ((node_x_t<53>*)nav)->setObject(index, nav);break;
        case 54: return ((node_x_t<54>*)nav)->setObject(index, nav);break;
        case 55: return ((node_x_t<55>*)nav)->setObject(index, nav);break;
        case 56: return ((node_x_t<56>*)nav)->setObject(index, nav);break;
        case 57: return ((node_x_t<57>*)nav)->setObject(index, nav);break;
        case 58: return ((node_x_t<58>*)nav)->setObject(index, nav);break;
        case 59: return ((node_x_t<59>*)nav)->setObject(index, nav);break;
        case 60: return ((node_x_t<60>*)nav)->setObject(index, nav);break;
        case 61: return ((node_x_t<61>*)nav)->setObject(index, nav);break;
        case 62: return ((node_x_t<62>*)nav)->setObject(index, nav);break;
        case 63: return ((node_x_t<63>*)nav)->setObject(index, nav);break;
        case 64: return ((node_x_t<64>*)nav)->setObject(index, nav);break;
        case 65: return ((node_x_t<65>*)nav)->setObject(index, nav);break;
        case 66: return ((node_x_t<66>*)nav)->setObject(index, nav);break;
        case 67: return ((node_x_t<67>*)nav)->setObject(index, nav);break;
        case 68: return ((node_x_t<68>*)nav)->setObject(index, nav);break;
        case 69: return ((node_x_t<69>*)nav)->setObject(index, nav);break;
        case 70: return ((node_x_t<70>*)nav)->setObject(index, nav);break;
        case 71: return ((node_x_t<71>*)nav)->setObject(index, nav);break;
        case 72: return ((node_x_t<72>*)nav)->setObject(index, nav);break;
        case 73: return ((node_x_t<73>*)nav)->setObject(index, nav);break;
        case 74: return ((node_x_t<74>*)nav)->setObject(index, nav);break;
        case 75: return ((node_x_t<75>*)nav)->setObject(index, nav);break;
        case 76: return ((node_x_t<76>*)nav)->setObject(index, nav);break;
        case 77: return ((node_x_t<77>*)nav)->setObject(index, nav);break;
        case 78: return ((node_x_t<78>*)nav)->setObject(index, nav);break;
        case 79: return ((node_x_t<79>*)nav)->setObject(index, nav);break;
        case 80: return ((node_x_t<80>*)nav)->setObject(index, nav);break;
        case 81: return ((node_x_t<81>*)nav)->setObject(index, nav);break;
        case 82: return ((node_x_t<82>*)nav)->setObject(index, nav);break;
        case 83: return ((node_x_t<83>*)nav)->setObject(index, nav);break;
        case 84: return ((node_x_t<84>*)nav)->setObject(index, nav);break;
        case 85: return ((node_x_t<85>*)nav)->setObject(index, nav);break;
        case 86: return ((node_x_t<86>*)nav)->setObject(index, nav);break;
        case 87: return ((node_x_t<87>*)nav)->setObject(index, nav);break;
        case 88: return ((node_x_t<88>*)nav)->setObject(index, nav);break;
        case 89: return ((node_x_t<89>*)nav)->setObject(index, nav);break;
        case 90: return ((node_x_t<90>*)nav)->setObject(index, nav);break;
        case 91: return ((node_x_t<91>*)nav)->setObject(index, nav);break;
        case 92: return ((node_x_t<92>*)nav)->setObject(index, nav);break;
        case 93: return ((node_x_t<93>*)nav)->setObject(index, nav);break;
        case 94: return ((node_x_t<94>*)nav)->setObject(index, nav);break;
        case 95: return ((node_x_t<95>*)nav)->setObject(index, nav);break;
        case 96: return ((node_x_t<96>*)nav)->setObject(index, nav);break;
        case 97: return ((node_x_t<97>*)nav)->setObject(index, nav);break;
        case 98: return ((node_x_t<98>*)nav)->setObject(index, nav);break;
        case 99: return ((node_x_t<99>*)nav)->setObject(index, nav);break;
        case 100: return ((node_x_t<100>*)nav)->setObject(index, nav);break;
        case 101: return ((node_x_t<101>*)nav)->setObject(index, nav);break;
        case 102: return ((node_x_t<102>*)nav)->setObject(index, nav);break;
        case 103: return ((node_x_t<103>*)nav)->setObject(index, nav);break;
        case 104: return ((node_x_t<104>*)nav)->setObject(index, nav);break;
        case 105: return ((node_x_t<105>*)nav)->setObject(index, nav);break;
        case 106: return ((node_x_t<106>*)nav)->setObject(index, nav);break;
        case 107: return ((node_x_t<107>*)nav)->setObject(index, nav);break;
        case 108: return ((node_x_t<108>*)nav)->setObject(index, nav);break;
        case 109: return ((node_x_t<109>*)nav)->setObject(index, nav);break;
        case 110: return ((node_x_t<110>*)nav)->setObject(index, nav);break;
        case 111: return ((node_x_t<111>*)nav)->setObject(index, nav);break;
        case 112: return ((node_x_t<112>*)nav)->setObject(index, nav);break;
        case 113: return ((node_x_t<113>*)nav)->setObject(index, nav);break;
        case 114: return ((node_x_t<114>*)nav)->setObject(index, nav);break;
        case 115: return ((node_x_t<115>*)nav)->setObject(index, nav);break;
        case 116: return ((node_x_t<116>*)nav)->setObject(index, nav);break;
        case 117: return ((node_x_t<117>*)nav)->setObject(index, nav);break;
        case 118: return ((node_x_t<118>*)nav)->setObject(index, nav);break;
        case 119: return ((node_x_t<119>*)nav)->setObject(index, nav);break;
        case 120: return ((node_x_t<120>*)nav)->setObject(index, nav);break;
        case 121: return ((node_x_t<121>*)nav)->setObject(index, nav);break;
        case 122: return ((node_x_t<122>*)nav)->setObject(index, nav);break;
        case 123: return ((node_x_t<123>*)nav)->setObject(index, nav);break;
        case 124: return ((node_x_t<124>*)nav)->setObject(index, nav);break;
        case 125: return ((node_x_t<125>*)nav)->setObject(index, nav);break;
        case 126: return ((node_x_t<126>*)nav)->setObject(index, nav);break;
        case 127: return ((node_x_t<127>*)nav)->setObject(index, nav);break;
        case 128: return ((node_x_t<128>*)nav)->setObject(index, nav);break;
        case 129: return ((node_x_t<129>*)nav)->setObject(index, nav);break;
        case 130: return ((node_x_t<130>*)nav)->setObject(index, nav);break;
        case 131: return ((node_x_t<131>*)nav)->setObject(index, nav);break;
        case 132: return ((node_x_t<132>*)nav)->setObject(index, nav);break;
        case 133: return ((node_x_t<133>*)nav)->setObject(index, nav);break;
        case 134: return ((node_x_t<134>*)nav)->setObject(index, nav);break;
        case 135: return ((node_x_t<135>*)nav)->setObject(index, nav);break;
        case 136: return ((node_x_t<136>*)nav)->setObject(index, nav);break;
        case 137: return ((node_x_t<137>*)nav)->setObject(index, nav);break;
        case 138: return ((node_x_t<138>*)nav)->setObject(index, nav);break;
        case 139: return ((node_x_t<139>*)nav)->setObject(index, nav);break;
        case 140: return ((node_x_t<140>*)nav)->setObject(index, nav);break;
        case 141: return ((node_x_t<141>*)nav)->setObject(index, nav);break;
        case 142: return ((node_x_t<142>*)nav)->setObject(index, nav);break;
        case 143: return ((node_x_t<143>*)nav)->setObject(index, nav);break;
        case 144: return ((node_x_t<144>*)nav)->setObject(index, nav);break;
        case 145: return ((node_x_t<145>*)nav)->setObject(index, nav);break;
        case 146: return ((node_x_t<146>*)nav)->setObject(index, nav);break;
        case 147: return ((node_x_t<147>*)nav)->setObject(index, nav);break;
        case 148: return ((node_x_t<148>*)nav)->setObject(index, nav);break;
        case 149: return ((node_x_t<149>*)nav)->setObject(index, nav);break;
        case 150: return ((node_x_t<150>*)nav)->setObject(index, nav);break;
        case 151: return ((node_x_t<151>*)nav)->setObject(index, nav);break;
        case 152: return ((node_x_t<152>*)nav)->setObject(index, nav);break;
        case 153: return ((node_x_t<153>*)nav)->setObject(index, nav);break;
        case 154: return ((node_x_t<154>*)nav)->setObject(index, nav);break;
        case 155: return ((node_x_t<155>*)nav)->setObject(index, nav);break;
        case 156: return ((node_x_t<156>*)nav)->setObject(index, nav);break;
        case 157: return ((node_x_t<157>*)nav)->setObject(index, nav);break;
        case 158: return ((node_x_t<158>*)nav)->setObject(index, nav);break;
        case 159: return ((node_x_t<159>*)nav)->setObject(index, nav);break;
        case 160: return ((node_x_t<160>*)nav)->setObject(index, nav);break;
        case 161: return ((node_x_t<161>*)nav)->setObject(index, nav);break;
        case 162: return ((node_x_t<162>*)nav)->setObject(index, nav);break;
        case 163: return ((node_x_t<163>*)nav)->setObject(index, nav);break;
        case 164: return ((node_x_t<164>*)nav)->setObject(index, nav);break;
        case 165: return ((node_x_t<165>*)nav)->setObject(index, nav);break;
        case 166: return ((node_x_t<166>*)nav)->setObject(index, nav);break;
        case 167: return ((node_x_t<167>*)nav)->setObject(index, nav);break;
        case 168: return ((node_x_t<168>*)nav)->setObject(index, nav);break;
        case 169: return ((node_x_t<169>*)nav)->setObject(index, nav);break;
        case 170: return ((node_x_t<170>*)nav)->setObject(index, nav);break;
        case 171: return ((node_x_t<171>*)nav)->setObject(index, nav);break;
        case 172: return ((node_x_t<172>*)nav)->setObject(index, nav);break;
        case 173: return ((node_x_t<173>*)nav)->setObject(index, nav);break;
        case 174: return ((node_x_t<174>*)nav)->setObject(index, nav);break;
        case 175: return ((node_x_t<175>*)nav)->setObject(index, nav);break;
        case 176: return ((node_x_t<176>*)nav)->setObject(index, nav);break;
        case 177: return ((node_x_t<177>*)nav)->setObject(index, nav);break;
        case 178: return ((node_x_t<178>*)nav)->setObject(index, nav);break;
        case 179: return ((node_x_t<179>*)nav)->setObject(index, nav);break;
        case 180: return ((node_x_t<180>*)nav)->setObject(index, nav);break;
        case 181: return ((node_x_t<181>*)nav)->setObject(index, nav);break;
        case 182: return ((node_x_t<182>*)nav)->setObject(index, nav);break;
        case 183: return ((node_x_t<183>*)nav)->setObject(index, nav);break;
        case 184: return ((node_x_t<184>*)nav)->setObject(index, nav);break;
        case 185: return ((node_x_t<185>*)nav)->setObject(index, nav);break;
        case 186: return ((node_x_t<186>*)nav)->setObject(index, nav);break;
        case 187: return ((node_x_t<187>*)nav)->setObject(index, nav);break;
        case 188: return ((node_x_t<188>*)nav)->setObject(index, nav);break;
        case 189: return ((node_x_t<189>*)nav)->setObject(index, nav);break;
        case 190: return ((node_x_t<190>*)nav)->setObject(index, nav);break;
        case 191: return ((node_x_t<191>*)nav)->setObject(index, nav);break;
        case 192: return ((node_x_t<192>*)nav)->setObject(index, nav);break;
        case 193: return ((node_x_t<193>*)nav)->setObject(index, nav);break;
        case 194: return ((node_x_t<194>*)nav)->setObject(index, nav);break;
        case 195: return ((node_x_t<195>*)nav)->setObject(index, nav);break;
        case 196: return ((node_x_t<196>*)nav)->setObject(index, nav);break;
        case 197: return ((node_x_t<197>*)nav)->setObject(index, nav);break;
        case 198: return ((node_x_t<198>*)nav)->setObject(index, nav);break;
        case 199: return ((node_x_t<199>*)nav)->setObject(index, nav);break;
        case 200: return ((node_x_t<200>*)nav)->setObject(index, nav);break;
        case 201: return ((node_x_t<201>*)nav)->setObject(index, nav);break;
        case 202: return ((node_x_t<202>*)nav)->setObject(index, nav);break;
        case 203: return ((node_x_t<203>*)nav)->setObject(index, nav);break;
        case 204: return ((node_x_t<204>*)nav)->setObject(index, nav);break;
        case 205: return ((node_x_t<205>*)nav)->setObject(index, nav);break;
        case 206: return ((node_x_t<206>*)nav)->setObject(index, nav);break;
        case 207: return ((node_x_t<207>*)nav)->setObject(index, nav);break;
        case 208: return ((node_x_t<208>*)nav)->setObject(index, nav);break;
        case 209: return ((node_x_t<209>*)nav)->setObject(index, nav);break;
        case 210: return ((node_x_t<210>*)nav)->setObject(index, nav);break;
        case 211: return ((node_x_t<211>*)nav)->setObject(index, nav);break;
        case 212: return ((node_x_t<212>*)nav)->setObject(index, nav);break;
        case 213: return ((node_x_t<213>*)nav)->setObject(index, nav);break;
        case 214: return ((node_x_t<214>*)nav)->setObject(index, nav);break;
        case 215: return ((node_x_t<215>*)nav)->setObject(index, nav);break;
        case 216: return ((node_x_t<216>*)nav)->setObject(index, nav);break;
        case 217: return ((node_x_t<217>*)nav)->setObject(index, nav);break;
        case 218: return ((node_x_t<218>*)nav)->setObject(index, nav);break;
        case 219: return ((node_x_t<219>*)nav)->setObject(index, nav);break;
        case 220: return ((node_x_t<220>*)nav)->setObject(index, nav);break;
        case 221: return ((node_x_t<221>*)nav)->setObject(index, nav);break;
        case 222: return ((node_x_t<222>*)nav)->setObject(index, nav);break;
        case 223: return ((node_x_t<223>*)nav)->setObject(index, nav);break;
        case 224: return ((node_x_t<224>*)nav)->setObject(index, nav);break;
        case 225: return ((node_x_t<225>*)nav)->setObject(index, nav);break;
        case 226: return ((node_x_t<226>*)nav)->setObject(index, nav);break;
        case 227: return ((node_x_t<227>*)nav)->setObject(index, nav);break;
        case 228: return ((node_x_t<228>*)nav)->setObject(index, nav);break;
        case 229: return ((node_x_t<229>*)nav)->setObject(index, nav);break;
        case 230: return ((node_x_t<230>*)nav)->setObject(index, nav);break;
        case 231: return ((node_x_t<231>*)nav)->setObject(index, nav);break;
        case 232: return ((node_x_t<232>*)nav)->setObject(index, nav);break;
        case 233: return ((node_x_t<233>*)nav)->setObject(index, nav);break;
        case 234: return ((node_x_t<234>*)nav)->setObject(index, nav);break;
        case 235: return ((node_x_t<235>*)nav)->setObject(index, nav);break;
        case 236: return ((node_x_t<236>*)nav)->setObject(index, nav);break;
        case 237: return ((node_x_t<237>*)nav)->setObject(index, nav);break;
        case 238: return ((node_x_t<238>*)nav)->setObject(index, nav);break;
        case 239: return ((node_x_t<239>*)nav)->setObject(index, nav);break;
        case 240: return ((node_x_t<240>*)nav)->setObject(index, nav);break;
        case 241: return ((node_x_t<241>*)nav)->setObject(index, nav);break;
        case 242: return ((node_x_t<242>*)nav)->setObject(index, nav);break;
        case 243: return ((node_x_t<243>*)nav)->setObject(index, nav);break;
        case 244: return ((node_x_t<244>*)nav)->setObject(index, nav);break;
        case 245: return ((node_x_t<245>*)nav)->setObject(index, nav);break;
        case 246: return ((node_x_t<246>*)nav)->setObject(index, nav);break;
        case 247: return ((node_x_t<247>*)nav)->setObject(index, nav);break;
        case 248: return ((node_x_t<248>*)nav)->setObject(index, nav);break;
        case 249: return ((node_x_t<249>*)nav)->setObject(index, nav);break;
        case 250: return ((node_x_t<250>*)nav)->setObject(index, nav);break;
        case 251: return ((node_x_t<251>*)nav)->setObject(index, nav);break;
        case 252: return ((node_x_t<252>*)nav)->setObject(index, nav);break;
        case 253: return ((node_x_t<253>*)nav)->setObject(index, nav);break;
        case 254: return ((node_x_t<254>*)nav)->setObject(index, nav);break;
        case 255: return ((node_x_t<255>*)nav)->setObject(index, nav);break;
    }
    return NULL;
}

void setChildUtil(size_t index, node_t* child, void* prev){
    switch(static_cast<node_t*>(prev)->num_elements) {
        case 1:static_cast<node_x_t<1>*>(prev)->setChild(index, child, prev);break;
        case 2:static_cast<node_x_t<2>*>(prev)->setChild(index, child, prev);break;
        case 3:static_cast<node_x_t<3>*>(prev)->setChild(index, child, prev);break;
        case 4:static_cast<node_x_t<4>*>(prev)->setChild(index, child, prev);break;
        case 5:static_cast<node_x_t<5>*>(prev)->setChild(index, child, prev);break;
        case 6:static_cast<node_x_t<6>*>(prev)->setChild(index, child, prev);break;
        case 7:static_cast<node_x_t<7>*>(prev)->setChild(index, child, prev);break;
        case 8:static_cast<node_x_t<8>*>(prev)->setChild(index, child, prev);break;
        case 9:static_cast<node_x_t<9>*>(prev)->setChild(index, child, prev);break;
        case 10:static_cast<node_x_t<10>*>(prev)->setChild(index, child, prev);break;
        case 11:static_cast<node_x_t<11>*>(prev)->setChild(index, child, prev);break;
        case 12:static_cast<node_x_t<12>*>(prev)->setChild(index, child, prev);break;
        case 13:static_cast<node_x_t<13>*>(prev)->setChild(index, child, prev);break;
        case 14:static_cast<node_x_t<14>*>(prev)->setChild(index, child, prev);break;
        case 15:static_cast<node_x_t<15>*>(prev)->setChild(index, child, prev);break;
        case 16:static_cast<node_x_t<16>*>(prev)->setChild(index, child, prev);break;
        case 17:static_cast<node_x_t<17>*>(prev)->setChild(index, child, prev);break;
        case 18:static_cast<node_x_t<18>*>(prev)->setChild(index, child, prev);break;
        case 19:static_cast<node_x_t<19>*>(prev)->setChild(index, child, prev);break;
        case 20:static_cast<node_x_t<20>*>(prev)->setChild(index, child, prev);break;
        case 21:static_cast<node_x_t<21>*>(prev)->setChild(index, child, prev);break;
        case 22:static_cast<node_x_t<22>*>(prev)->setChild(index, child, prev);break;
        case 23:static_cast<node_x_t<23>*>(prev)->setChild(index, child, prev);break;
        case 24:static_cast<node_x_t<24>*>(prev)->setChild(index, child, prev);break;
        case 25:static_cast<node_x_t<25>*>(prev)->setChild(index, child, prev);break;
        case 26:static_cast<node_x_t<26>*>(prev)->setChild(index, child, prev);break;
        case 27:static_cast<node_x_t<27>*>(prev)->setChild(index, child, prev);break;
        case 28:static_cast<node_x_t<28>*>(prev)->setChild(index, child, prev);break;
        case 29:static_cast<node_x_t<29>*>(prev)->setChild(index, child, prev);break;
        case 30:static_cast<node_x_t<30>*>(prev)->setChild(index, child, prev);break;
        case 31:static_cast<node_x_t<31>*>(prev)->setChild(index, child, prev);break;
        case 32:static_cast<node_x_t<32>*>(prev)->setChild(index, child, prev);break;
        case 33:static_cast<node_x_t<33>*>(prev)->setChild(index, child, prev);break;
        case 34:static_cast<node_x_t<34>*>(prev)->setChild(index, child, prev);break;
        case 35:static_cast<node_x_t<35>*>(prev)->setChild(index, child, prev);break;
        case 36:static_cast<node_x_t<36>*>(prev)->setChild(index, child, prev);break;
        case 37:static_cast<node_x_t<37>*>(prev)->setChild(index, child, prev);break;
        case 38:static_cast<node_x_t<38>*>(prev)->setChild(index, child, prev);break;
        case 39:static_cast<node_x_t<39>*>(prev)->setChild(index, child, prev);break;
        case 40:static_cast<node_x_t<40>*>(prev)->setChild(index, child, prev);break;
        case 41:static_cast<node_x_t<41>*>(prev)->setChild(index, child, prev);break;
        case 42:static_cast<node_x_t<42>*>(prev)->setChild(index, child, prev);break;
        case 43:static_cast<node_x_t<43>*>(prev)->setChild(index, child, prev);break;
        case 44:static_cast<node_x_t<44>*>(prev)->setChild(index, child, prev);break;
        case 45:static_cast<node_x_t<45>*>(prev)->setChild(index, child, prev);break;
        case 46:static_cast<node_x_t<46>*>(prev)->setChild(index, child, prev);break;
        case 47:static_cast<node_x_t<47>*>(prev)->setChild(index, child, prev);break;
        case 48:static_cast<node_x_t<48>*>(prev)->setChild(index, child, prev);break;
        case 49:static_cast<node_x_t<49>*>(prev)->setChild(index, child, prev);break;
        case 50:static_cast<node_x_t<50>*>(prev)->setChild(index, child, prev);break;
        case 51:static_cast<node_x_t<51>*>(prev)->setChild(index, child, prev);break;
        case 52:static_cast<node_x_t<52>*>(prev)->setChild(index, child, prev);break;
        case 53:static_cast<node_x_t<53>*>(prev)->setChild(index, child, prev);break;
        case 54:static_cast<node_x_t<54>*>(prev)->setChild(index, child, prev);break;
        case 55:static_cast<node_x_t<55>*>(prev)->setChild(index, child, prev);break;
        case 56:static_cast<node_x_t<56>*>(prev)->setChild(index, child, prev);break;
        case 57:static_cast<node_x_t<57>*>(prev)->setChild(index, child, prev);break;
        case 58:static_cast<node_x_t<58>*>(prev)->setChild(index, child, prev);break;
        case 59:static_cast<node_x_t<59>*>(prev)->setChild(index, child, prev);break;
        case 60:static_cast<node_x_t<60>*>(prev)->setChild(index, child, prev);break;
        case 61:static_cast<node_x_t<61>*>(prev)->setChild(index, child, prev);break;
        case 62:static_cast<node_x_t<62>*>(prev)->setChild(index, child, prev);break;
        case 63:static_cast<node_x_t<63>*>(prev)->setChild(index, child, prev);break;
        case 64:static_cast<node_x_t<64>*>(prev)->setChild(index, child, prev);break;
        case 65:static_cast<node_x_t<65>*>(prev)->setChild(index, child, prev);break;
        case 66:static_cast<node_x_t<66>*>(prev)->setChild(index, child, prev);break;
        case 67:static_cast<node_x_t<67>*>(prev)->setChild(index, child, prev);break;
        case 68:static_cast<node_x_t<68>*>(prev)->setChild(index, child, prev);break;
        case 69:static_cast<node_x_t<69>*>(prev)->setChild(index, child, prev);break;
        case 70:static_cast<node_x_t<70>*>(prev)->setChild(index, child, prev);break;
        case 71:static_cast<node_x_t<71>*>(prev)->setChild(index, child, prev);break;
        case 72:static_cast<node_x_t<72>*>(prev)->setChild(index, child, prev);break;
        case 73:static_cast<node_x_t<73>*>(prev)->setChild(index, child, prev);break;
        case 74:static_cast<node_x_t<74>*>(prev)->setChild(index, child, prev);break;
        case 75:static_cast<node_x_t<75>*>(prev)->setChild(index, child, prev);break;
        case 76:static_cast<node_x_t<76>*>(prev)->setChild(index, child, prev);break;
        case 77:static_cast<node_x_t<77>*>(prev)->setChild(index, child, prev);break;
        case 78:static_cast<node_x_t<78>*>(prev)->setChild(index, child, prev);break;
        case 79:static_cast<node_x_t<79>*>(prev)->setChild(index, child, prev);break;
        case 80:static_cast<node_x_t<80>*>(prev)->setChild(index, child, prev);break;
        case 81:static_cast<node_x_t<81>*>(prev)->setChild(index, child, prev);break;
        case 82:static_cast<node_x_t<82>*>(prev)->setChild(index, child, prev);break;
        case 83:static_cast<node_x_t<83>*>(prev)->setChild(index, child, prev);break;
        case 84:static_cast<node_x_t<84>*>(prev)->setChild(index, child, prev);break;
        case 85:static_cast<node_x_t<85>*>(prev)->setChild(index, child, prev);break;
        case 86:static_cast<node_x_t<86>*>(prev)->setChild(index, child, prev);break;
        case 87:static_cast<node_x_t<87>*>(prev)->setChild(index, child, prev);break;
        case 88:static_cast<node_x_t<88>*>(prev)->setChild(index, child, prev);break;
        case 89:static_cast<node_x_t<89>*>(prev)->setChild(index, child, prev);break;
        case 90:static_cast<node_x_t<90>*>(prev)->setChild(index, child, prev);break;
        case 91:static_cast<node_x_t<91>*>(prev)->setChild(index, child, prev);break;
        case 92:static_cast<node_x_t<92>*>(prev)->setChild(index, child, prev);break;
        case 93:static_cast<node_x_t<93>*>(prev)->setChild(index, child, prev);break;
        case 94:static_cast<node_x_t<94>*>(prev)->setChild(index, child, prev);break;
        case 95:static_cast<node_x_t<95>*>(prev)->setChild(index, child, prev);break;
        case 96:static_cast<node_x_t<96>*>(prev)->setChild(index, child, prev);break;
        case 97:static_cast<node_x_t<97>*>(prev)->setChild(index, child, prev);break;
        case 98:static_cast<node_x_t<98>*>(prev)->setChild(index, child, prev);break;
        case 99:static_cast<node_x_t<99>*>(prev)->setChild(index, child, prev);break;
        case 100:static_cast<node_x_t<100>*>(prev)->setChild(index, child, prev);break;
        case 101:static_cast<node_x_t<101>*>(prev)->setChild(index, child, prev);break;
        case 102:static_cast<node_x_t<102>*>(prev)->setChild(index, child, prev);break;
        case 103:static_cast<node_x_t<103>*>(prev)->setChild(index, child, prev);break;
        case 104:static_cast<node_x_t<104>*>(prev)->setChild(index, child, prev);break;
        case 105:static_cast<node_x_t<105>*>(prev)->setChild(index, child, prev);break;
        case 106:static_cast<node_x_t<106>*>(prev)->setChild(index, child, prev);break;
        case 107:static_cast<node_x_t<107>*>(prev)->setChild(index, child, prev);break;
        case 108:static_cast<node_x_t<108>*>(prev)->setChild(index, child, prev);break;
        case 109:static_cast<node_x_t<109>*>(prev)->setChild(index, child, prev);break;
        case 110:static_cast<node_x_t<110>*>(prev)->setChild(index, child, prev);break;
        case 111:static_cast<node_x_t<111>*>(prev)->setChild(index, child, prev);break;
        case 112:static_cast<node_x_t<112>*>(prev)->setChild(index, child, prev);break;
        case 113:static_cast<node_x_t<113>*>(prev)->setChild(index, child, prev);break;
        case 114:static_cast<node_x_t<114>*>(prev)->setChild(index, child, prev);break;
        case 115:static_cast<node_x_t<115>*>(prev)->setChild(index, child, prev);break;
        case 116:static_cast<node_x_t<116>*>(prev)->setChild(index, child, prev);break;
        case 117:static_cast<node_x_t<117>*>(prev)->setChild(index, child, prev);break;
        case 118:static_cast<node_x_t<118>*>(prev)->setChild(index, child, prev);break;
        case 119:static_cast<node_x_t<119>*>(prev)->setChild(index, child, prev);break;
        case 120:static_cast<node_x_t<120>*>(prev)->setChild(index, child, prev);break;
        case 121:static_cast<node_x_t<121>*>(prev)->setChild(index, child, prev);break;
        case 122:static_cast<node_x_t<122>*>(prev)->setChild(index, child, prev);break;
        case 123:static_cast<node_x_t<123>*>(prev)->setChild(index, child, prev);break;
        case 124:static_cast<node_x_t<124>*>(prev)->setChild(index, child, prev);break;
        case 125:static_cast<node_x_t<125>*>(prev)->setChild(index, child, prev);break;
        case 126:static_cast<node_x_t<126>*>(prev)->setChild(index, child, prev);break;
        case 127:static_cast<node_x_t<127>*>(prev)->setChild(index, child, prev);break;
        case 128:static_cast<node_x_t<128>*>(prev)->setChild(index, child, prev);break;
        case 129:static_cast<node_x_t<129>*>(prev)->setChild(index, child, prev);break;
        case 130:static_cast<node_x_t<130>*>(prev)->setChild(index, child, prev);break;
        case 131:static_cast<node_x_t<131>*>(prev)->setChild(index, child, prev);break;
        case 132:static_cast<node_x_t<132>*>(prev)->setChild(index, child, prev);break;
        case 133:static_cast<node_x_t<133>*>(prev)->setChild(index, child, prev);break;
        case 134:static_cast<node_x_t<134>*>(prev)->setChild(index, child, prev);break;
        case 135:static_cast<node_x_t<135>*>(prev)->setChild(index, child, prev);break;
        case 136:static_cast<node_x_t<136>*>(prev)->setChild(index, child, prev);break;
        case 137:static_cast<node_x_t<137>*>(prev)->setChild(index, child, prev);break;
        case 138:static_cast<node_x_t<138>*>(prev)->setChild(index, child, prev);break;
        case 139:static_cast<node_x_t<139>*>(prev)->setChild(index, child, prev);break;
        case 140:static_cast<node_x_t<140>*>(prev)->setChild(index, child, prev);break;
        case 141:static_cast<node_x_t<141>*>(prev)->setChild(index, child, prev);break;
        case 142:static_cast<node_x_t<142>*>(prev)->setChild(index, child, prev);break;
        case 143:static_cast<node_x_t<143>*>(prev)->setChild(index, child, prev);break;
        case 144:static_cast<node_x_t<144>*>(prev)->setChild(index, child, prev);break;
        case 145:static_cast<node_x_t<145>*>(prev)->setChild(index, child, prev);break;
        case 146:static_cast<node_x_t<146>*>(prev)->setChild(index, child, prev);break;
        case 147:static_cast<node_x_t<147>*>(prev)->setChild(index, child, prev);break;
        case 148:static_cast<node_x_t<148>*>(prev)->setChild(index, child, prev);break;
        case 149:static_cast<node_x_t<149>*>(prev)->setChild(index, child, prev);break;
        case 150:static_cast<node_x_t<150>*>(prev)->setChild(index, child, prev);break;
        case 151:static_cast<node_x_t<151>*>(prev)->setChild(index, child, prev);break;
        case 152:static_cast<node_x_t<152>*>(prev)->setChild(index, child, prev);break;
        case 153:static_cast<node_x_t<153>*>(prev)->setChild(index, child, prev);break;
        case 154:static_cast<node_x_t<154>*>(prev)->setChild(index, child, prev);break;
        case 155:static_cast<node_x_t<155>*>(prev)->setChild(index, child, prev);break;
        case 156:static_cast<node_x_t<156>*>(prev)->setChild(index, child, prev);break;
        case 157:static_cast<node_x_t<157>*>(prev)->setChild(index, child, prev);break;
        case 158:static_cast<node_x_t<158>*>(prev)->setChild(index, child, prev);break;
        case 159:static_cast<node_x_t<159>*>(prev)->setChild(index, child, prev);break;
        case 160:static_cast<node_x_t<160>*>(prev)->setChild(index, child, prev);break;
        case 161:static_cast<node_x_t<161>*>(prev)->setChild(index, child, prev);break;
        case 162:static_cast<node_x_t<162>*>(prev)->setChild(index, child, prev);break;
        case 163:static_cast<node_x_t<163>*>(prev)->setChild(index, child, prev);break;
        case 164:static_cast<node_x_t<164>*>(prev)->setChild(index, child, prev);break;
        case 165:static_cast<node_x_t<165>*>(prev)->setChild(index, child, prev);break;
        case 166:static_cast<node_x_t<166>*>(prev)->setChild(index, child, prev);break;
        case 167:static_cast<node_x_t<167>*>(prev)->setChild(index, child, prev);break;
        case 168:static_cast<node_x_t<168>*>(prev)->setChild(index, child, prev);break;
        case 169:static_cast<node_x_t<169>*>(prev)->setChild(index, child, prev);break;
        case 170:static_cast<node_x_t<170>*>(prev)->setChild(index, child, prev);break;
        case 171:static_cast<node_x_t<171>*>(prev)->setChild(index, child, prev);break;
        case 172:static_cast<node_x_t<172>*>(prev)->setChild(index, child, prev);break;
        case 173:static_cast<node_x_t<173>*>(prev)->setChild(index, child, prev);break;
        case 174:static_cast<node_x_t<174>*>(prev)->setChild(index, child, prev);break;
        case 175:static_cast<node_x_t<175>*>(prev)->setChild(index, child, prev);break;
        case 176:static_cast<node_x_t<176>*>(prev)->setChild(index, child, prev);break;
        case 177:static_cast<node_x_t<177>*>(prev)->setChild(index, child, prev);break;
        case 178:static_cast<node_x_t<178>*>(prev)->setChild(index, child, prev);break;
        case 179:static_cast<node_x_t<179>*>(prev)->setChild(index, child, prev);break;
        case 180:static_cast<node_x_t<180>*>(prev)->setChild(index, child, prev);break;
        case 181:static_cast<node_x_t<181>*>(prev)->setChild(index, child, prev);break;
        case 182:static_cast<node_x_t<182>*>(prev)->setChild(index, child, prev);break;
        case 183:static_cast<node_x_t<183>*>(prev)->setChild(index, child, prev);break;
        case 184:static_cast<node_x_t<184>*>(prev)->setChild(index, child, prev);break;
        case 185:static_cast<node_x_t<185>*>(prev)->setChild(index, child, prev);break;
        case 186:static_cast<node_x_t<186>*>(prev)->setChild(index, child, prev);break;
        case 187:static_cast<node_x_t<187>*>(prev)->setChild(index, child, prev);break;
        case 188:static_cast<node_x_t<188>*>(prev)->setChild(index, child, prev);break;
        case 189:static_cast<node_x_t<189>*>(prev)->setChild(index, child, prev);break;
        case 190:static_cast<node_x_t<190>*>(prev)->setChild(index, child, prev);break;
        case 191:static_cast<node_x_t<191>*>(prev)->setChild(index, child, prev);break;
        case 192:static_cast<node_x_t<192>*>(prev)->setChild(index, child, prev);break;
        case 193:static_cast<node_x_t<193>*>(prev)->setChild(index, child, prev);break;
        case 194:static_cast<node_x_t<194>*>(prev)->setChild(index, child, prev);break;
        case 195:static_cast<node_x_t<195>*>(prev)->setChild(index, child, prev);break;
        case 196:static_cast<node_x_t<196>*>(prev)->setChild(index, child, prev);break;
        case 197:static_cast<node_x_t<197>*>(prev)->setChild(index, child, prev);break;
        case 198:static_cast<node_x_t<198>*>(prev)->setChild(index, child, prev);break;
        case 199:static_cast<node_x_t<199>*>(prev)->setChild(index, child, prev);break;
        case 200:static_cast<node_x_t<200>*>(prev)->setChild(index, child, prev);break;
        case 201:static_cast<node_x_t<201>*>(prev)->setChild(index, child, prev);break;
        case 202:static_cast<node_x_t<202>*>(prev)->setChild(index, child, prev);break;
        case 203:static_cast<node_x_t<203>*>(prev)->setChild(index, child, prev);break;
        case 204:static_cast<node_x_t<204>*>(prev)->setChild(index, child, prev);break;
        case 205:static_cast<node_x_t<205>*>(prev)->setChild(index, child, prev);break;
        case 206:static_cast<node_x_t<206>*>(prev)->setChild(index, child, prev);break;
        case 207:static_cast<node_x_t<207>*>(prev)->setChild(index, child, prev);break;
        case 208:static_cast<node_x_t<208>*>(prev)->setChild(index, child, prev);break;
        case 209:static_cast<node_x_t<209>*>(prev)->setChild(index, child, prev);break;
        case 210:static_cast<node_x_t<210>*>(prev)->setChild(index, child, prev);break;
        case 211:static_cast<node_x_t<211>*>(prev)->setChild(index, child, prev);break;
        case 212:static_cast<node_x_t<212>*>(prev)->setChild(index, child, prev);break;
        case 213:static_cast<node_x_t<213>*>(prev)->setChild(index, child, prev);break;
        case 214:static_cast<node_x_t<214>*>(prev)->setChild(index, child, prev);break;
        case 215:static_cast<node_x_t<215>*>(prev)->setChild(index, child, prev);break;
        case 216:static_cast<node_x_t<216>*>(prev)->setChild(index, child, prev);break;
        case 217:static_cast<node_x_t<217>*>(prev)->setChild(index, child, prev);break;
        case 218:static_cast<node_x_t<218>*>(prev)->setChild(index, child, prev);break;
        case 219:static_cast<node_x_t<219>*>(prev)->setChild(index, child, prev);break;
        case 220:static_cast<node_x_t<220>*>(prev)->setChild(index, child, prev);break;
        case 221:static_cast<node_x_t<221>*>(prev)->setChild(index, child, prev);break;
        case 222:static_cast<node_x_t<222>*>(prev)->setChild(index, child, prev);break;
        case 223:static_cast<node_x_t<223>*>(prev)->setChild(index, child, prev);break;
        case 224:static_cast<node_x_t<224>*>(prev)->setChild(index, child, prev);break;
        case 225:static_cast<node_x_t<225>*>(prev)->setChild(index, child, prev);break;
        case 226:static_cast<node_x_t<226>*>(prev)->setChild(index, child, prev);break;
        case 227:static_cast<node_x_t<227>*>(prev)->setChild(index, child, prev);break;
        case 228:static_cast<node_x_t<228>*>(prev)->setChild(index, child, prev);break;
        case 229:static_cast<node_x_t<229>*>(prev)->setChild(index, child, prev);break;
        case 230:static_cast<node_x_t<230>*>(prev)->setChild(index, child, prev);break;
        case 231:static_cast<node_x_t<231>*>(prev)->setChild(index, child, prev);break;
        case 232:static_cast<node_x_t<232>*>(prev)->setChild(index, child, prev);break;
        case 233:static_cast<node_x_t<233>*>(prev)->setChild(index, child, prev);break;
        case 234:static_cast<node_x_t<234>*>(prev)->setChild(index, child, prev);break;
        case 235:static_cast<node_x_t<235>*>(prev)->setChild(index, child, prev);break;
        case 236:static_cast<node_x_t<236>*>(prev)->setChild(index, child, prev);break;
        case 237:static_cast<node_x_t<237>*>(prev)->setChild(index, child, prev);break;
        case 238:static_cast<node_x_t<238>*>(prev)->setChild(index, child, prev);break;
        case 239:static_cast<node_x_t<239>*>(prev)->setChild(index, child, prev);break;
        case 240:static_cast<node_x_t<240>*>(prev)->setChild(index, child, prev);break;
        case 241:static_cast<node_x_t<241>*>(prev)->setChild(index, child, prev);break;
        case 242:static_cast<node_x_t<242>*>(prev)->setChild(index, child, prev);break;
        case 243:static_cast<node_x_t<243>*>(prev)->setChild(index, child, prev);break;
        case 244:static_cast<node_x_t<244>*>(prev)->setChild(index, child, prev);break;
        case 245:static_cast<node_x_t<245>*>(prev)->setChild(index, child, prev);break;
        case 246:static_cast<node_x_t<246>*>(prev)->setChild(index, child, prev);break;
        case 247:static_cast<node_x_t<247>*>(prev)->setChild(index, child, prev);break;
        case 248:static_cast<node_x_t<248>*>(prev)->setChild(index, child, prev);break;
        case 249:static_cast<node_x_t<249>*>(prev)->setChild(index, child, prev);break;
        case 250:static_cast<node_x_t<250>*>(prev)->setChild(index, child, prev);break;
        case 251:static_cast<node_x_t<251>*>(prev)->setChild(index, child, prev);break;
        case 252:static_cast<node_x_t<252>*>(prev)->setChild(index, child, prev);break;
        case 253:static_cast<node_x_t<253>*>(prev)->setChild(index, child, prev);break;
        case 254:static_cast<node_x_t<254>*>(prev)->setChild(index, child, prev);break;
        case 255:static_cast<node_x_t<255>*>(prev)->setChild(index, child, prev);break;
    }
}